language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

before_script:
  - cp phpunit-example.xml phpunit.xml
  - mysql -e 'create database commerce_testing'
  - composer install --no-interaction

script: vendor/bin/phpunit
