name: '🐛 Bug Report'
description: 'Found a bug? Submit a bug report.'
labels: [bug]
body:
- type: textarea
  attributes:
    label: Bug Description
    placeholder: 'What happened? What were you expecting? Feel free to add any screenshots in here.'
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: "There's no way for me to fix a bug if I don't know how to reproduce the bug in the first place."
    placeholder: |
        1. Do this thing...
        2. Then do that thing...
        3. And finally, do something else...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: Just copy and paste the output of the `php please support:details` command.
  validations:
    required: true
