blank_issues_enabled: false

contact_links:
  - name: 'Feature Request'
    url: https://github.com/doublethreedigital/simple-commerce/discussions/new
    about: Submit a feature request and chat about it with the community.
  - name: 'Community Help'
    url: https://github.com/doublethreedigital/simple-commerce/discussions
    about: 'Ask a question about Simple Commerce usage or anything Simple Commerce related.'
  - name: 'Support'
    url: mailto:hello@doublethree.digital
    about: 'To talk directly with the developers of this addon.'
