title: 'Simple Commerce: Product'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: description
        field:
          type: markdown
          localizable: false
          display: Description
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                character_limit: 0
                type: text
                localizable: false
                width: 50
                display: Name
            -
              handle: price
              field:
                type: money
                localizable: false
                width: 25
                display: Price
            -
              handle: sku
              field:
                generate: false
                type: slug
                localizable: false
                width: 25
                display: SKU
            -
              handle: max_quantity
              field:
                type: integer
                instructions: 'How many of these can a customer buy at once?'
                localizable: false
                width: 33
                display: 'Max Quantity'
            -
              handle: stock_number
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Stock Number'
                unless:
                  unlimited_stock: 'equals true'
                instructions: 'After every purchase, this number will be deducted from.'
            -
              handle: unlimited_stock
              field:
                type: toggle
                localizable: false
                width: 33
                display: 'Unlimited stock?'
            -
              handle: description
              field:
                type: markdown
                localizable: false
                display: Description
            -
              handle: variant_attributes
              field:
                fields:
                  -
                    handle: uuid
                    field:
                      character_limit: 0
                      type: hidden
                      localization: false
                      display: UUID
                  -
                    handle: key
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Key
                  -
                    handle: value
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Value
                mode: table
                reorderable: false
                type: grid
                localizable: false
                display: Attributes
                listable: true
                add_row: 'Add Attribute'
          mode: stacked
          min_rows: 1
          add_row: 'New Variant'
          reorderable: false
          type: grid
          localizable: false
          display: Variants
          listable: hidden
  attributes:
    display: Attributes
    fields:
      -
        handle: product_attributes
        field:
          fields:
            -
              handle: uuid
              field:
                type: hidden
                localizable: false
                listable: hidden
                display: UUID
            -
              handle: key
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Key
            -
              handle: value
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Value
          mode: table
          add_row: 'Add Attribute'
          reorderable: false
          type: grid
          localizable: false
          listable: true
          display: Attributes
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
      -
        handle: category
        field:
          max_items: 1
          mode: default
          type: product_category
          localizable: false
          display: 'Product Category'
      -
        handle: is_enabled
        field:
          type: toggle
          localizable: false
          display: 'Is Enabled?'
