title: 'Simple Commerce: Product'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
          listable: hidden
          input_type: text
          validate: required
      -
        handle: description
        field:
          type: markdown
          localizable: false
          display: Description
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                character_limit: 0
                type: text
                localizable: false
                display: 'Variant Name'
                listable: hidden
                input_type: text
                validate: required
            -
              handle: price
              field:
                type: money
                localizable: false
                width: 50
                display: Price
                listable: hidden
                validate: required
            -
              handle: sku
              field:
                generate: false
                type: slug
                localizable: false
                width: 50
                display: SKU
                listable: hidden
                validate: required
            -
              handle: max_quantity
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Max Quantity'
                listable: hidden
                validate: required
                default: 1
            -
              handle: stock_number
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Stock Number'
                listable: hidden
                unless:
                  unlimited_stock: 'equals true'
                validate: required
            -
              handle: unlimited_stock
              field:
                type: toggle
                localizable: false
                width: 33
                display: 'Unlimited stock?'
            -
              handle: description
              field:
                type: markdown
                localizable: false
                display: Description
            -
              import: variant_attributes
              prefix: attributes_
          mode: stacked
          min_rows: 1
          add_row: 'New Variant'
          reorderable: false
          type: grid
          localizable: false
          display: Variants
          listable: hidden
  attributes:
    display: Attributes
    fields:
      -
        handle: product_attributes
        field:
          fields:
            -
              handle: uuid
              field:
                type: hidden
                localizable: false
                listable: hidden
                display: UUID
            -
              handle: key
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Key
                input_type: text
                validate: required
            -
              handle: value
              field:
                html_type: text
                type: text
                localizable: false
                listable: hidden
                display: Value
                input_type: text
                validate: required
          mode: table
          add_row: 'Add Attribute'
          reorderable: false
          type: grid
          localizable: false
          listable: true
          display: Attributes
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
          listable: hidden
          validate: required
      -
        handle: category
        field:
          max_items: 1
          mode: default
          type: product_category
          localizable: false
          display: 'Product Category'
      -
        handle: is_enabled
        field:
          type: toggle
          localizable: false
          display: 'Is Enabled?'
