title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: gallery
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          localizable: false
          display: Gallery
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
          validate: required|string
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: true
          smartypants: false
          type: markdown
          localizable: false
          display: Description
  shipping:
    display: Shipping
    fields:
      -
        handle: free_shipping
        field:
          type: toggle
          localizable: false
          display: 'Free Shipping'
          width: 50
      -
        handle: shipping_price
        field:
          type: money
          localizable: false
          display: 'Shipping Price'
          width: 50
          unless:
            free_shipping: 'equals true'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: enabled
        field:
          type: toggle
          localizable: false
          display: 'Enabled?'
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
      -
        handle: publish_date
        field:
          time_enabled: true
          time_required: false
          earliest_date: '2019-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          mode: single
          type: date
          localizable: false
          display: 'Publish Date'
          validate: required
          width: 50
      -
        handle: expiry_date
        field:
          time_enabled: true
          time_required: false
          earliest_date: '2019-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          mode: single
          type: date
          localizable: false
          display: 'Expiry Date'
          width: 50
      -
        handle: price
        field:
          type: money
          localizable: false
          display: Price
      -
        handle: stock_number
        field:
          type: integer
          localizable: false
          display: 'Stock Number'
