title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                input_type: text
                type: text
                localizable: false
                width: 66
                listable: hidden
                display: Name
                factory: word
            -
              handle: sku
              field:
                input_type: text
                type: text
                localizable: false
                width: 33
                listable: hidden
                display: SKU
                factory: slug
            -
              handle: price
              field:
                input_type: text
                type: money
                localizable: false
                listable: hidden
                display: Price
                factory: 'numberBetween(20, 50)'
            -
              handle: description
              field:
                type: textarea
                localizable: false
                listable: hidden
                display: Description
                factory: 'paragraphs(3, true)'
            -
              handle: stock
              field:
                input_type: number
                type: text
                localizable: false
                listable: hidden
                display: Stock
          mode: stacked
          min_rows: 1
          reorderable: false
          type: grid
          localizable: false
          listable: hidden
          display: Variants
          purchasable: true
