title: 'Product Category'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
