title: 'Simple Commerce: Product'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Title
      -
        handle: description
        field:
          type: textarea
          localizable: false
          display: Description
      -
        handle: variants
        field:
          fields:
            -
              handle: name
              field:
                character_limit: 0
                type: text
                localizable: false
                width: 50
                display: Name
            -
              handle: price
              field:
                type: money
                localizable: false
                width: 25
                display: Price
            -
              handle: sku
              field:
                generate: true
                type: slug
                localizable: false
                width: 25
                display: SKU
            -
              handle: max_quantity
              field:
                type: integer
                instructions: 'How many of these can a customer buy at once?'
                localizable: false
                width: 33
                display: 'Max Quantity'
            -
              handle: stock_number
              field:
                type: integer
                localizable: false
                width: 33
                display: 'Stock Number'
                unless:
                  unlimited_stock: 'equals true'
                instructions: 'After every purchase, this number will be deducted from.'
            -
              handle: unlimited_stock
              field:
                type: toggle
                localizable: false
                width: 33
                display: 'Unlimited stock?'
            -
              handle: description
              field:
                type: textarea
                localizable: false
                display: Description
            -
              handle: variant_attributes
              field:
                fields:
                  -
                    handle: uuid
                    field:
                      character_limit: 0
                      type: hidden
                      localizable: false
                      display: UUID
                  -
                    handle: key
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Key
                  -
                    handle: value
                    field:
                      character_limit: 0
                      type: text
                      localizable: false
                      display: Value
                mode: table
                max_rows: 0
                min_rows: 4
                reorderable: true
                type: grid
                localizable: false
                display: Attributes
          mode: stacked
          max_rows: 0
          min_rows: 2
          add_row: 'New Variant'
          reorderable: true
          type: grid
          localizable: false
          display: Variants
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          display: Slug
      -
        handle: category
        field:
          max_items: 1
          mode: default
          type: product_category
          localizable: false
          display: 'Product Category'
