name: 'Install Checkup'

# This workflow can automate the process of installing Simple Commerce in projects.
# Currently it tests that the Simple Commerce starter kit installs itself properly &
# it also tests that Simple Commerce can be installed in a fresh install of
# statamic/statamic.

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  installViaStarterKit:
    name: Install via Starter Kit
    runs-on: ubuntu-latest
    steps:
      - name: Clone doublethreedigital/sc-starter-kit from GitHub
        uses: actions/checkout@v2
        with:
          repository: doublethreedigital/sc-starter-kit
          path: 'sc-starter-kit'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2

      - name: Install Composer Dependencies
        run: cd sc-starter-kit && composer install

      - name: Copy .env.example to .env
        run: cd sc-starter-kit && cp .env.example .env

      - name: Generate APP_KEY
        run: cd sc-starter-kit && php artisan key:generate

      - name: Install NPM Dependencies
        run: cd sc-starter-kit && npm install

      - name: Compile assets
        run: cd sc-starter-kit && npm run production

  installInExistingStatamicSite:
    name: Install in Existing Statamic Site
    runs-on: ubuntu-latest
    steps:
      - name: Clone statamic/statamic from GitHub
        uses: actions/checkout@v2
        with:
          repository: statamic/statamic
          path: 'statamic'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2

      - name: Install Composer Dependencies
        run: cd statamic && composer install

      - name: Copy .env.example to .env
        run: cd statamic && cp .env.example .env

      - name: Generate APP_KEY
        run: cd statamic && php artisan key:generate

      - name: Require Simple Commerce
        run: cd statamic && composer require doublethreedigital/simple-commerce

      - name: Install Simple Commerce
        run: cd statamic && php please sc:install
