name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Shutdown Ubuntu MySQL
      run: sudo service mysql stop

    - name: Setup database
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '5.7'
        mysql database: 'simple-commerce-testing'
        mysql root password: 'a.k-ZWzdKyWw@QyeP6rKAxg*'
        mysql user: 'root'
        mysql password: null

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Install dependencies
      run: |
        composer validate
        composer install --no-interaction

    - name: Run PHPUnit
      run: composer test
