name: Test Suite

on:
  push:
  pull_request:

jobs:
  phpunit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHPUnit config
      run: cp phpunit-example.xml phpunit.xml

    - name: Setup database
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'commerce_testing'
        mysql root password: 'a.k-ZWzdKyWw@QyeP6rKAxg*'
        mysql user: 'root'
        mysql password: 'a.k-ZWzdKyWw@QyeP6rKAxg*'

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extension-csv: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Install dependencies
      run: |
        composer validate
        composer install --no-interaction

    - name: Run PHPUnit
      run: composer test

    - name: Send Slack notification
      uses: 8398a7/action-slack@v2
      if: failure()
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
